### ISSUE TITLE
Category name translation

### ISSUE THREAD

**Issue by ckappgit** [DevToys-app/DevToys#1301] opened 2024-07-16 03:13 UTC
### What improvement do you think would an existing feature or tool in DevToys?

There is currently no corresponding translation file for the tool category name
<img width="261" alt="2024-07-16_11-11" src="https://github.com/user-attachments/assets/2748b6ea-6983-4f5f-9c6f-636cb7e1e998">

### Solution/Idea

Make category names translatable

**Comment by veler** [comment] 2024-08-10 16:54
I reproduced the issue with many languages. This looks like a bug.

**Comment by veler** [comment] 2024-08-11 04:03
Seems like an issue with Crowdin: https://community.crowdin.com/t/one-file-does-not-appear-in-sources-but-appear-in-branch-configuration/9463

**Comment by veler** [comment] 2024-08-11 04:17
Partially fixed in https://github.com/DevToys-app/DevToys/pull/1369

**Comment by veler** [comment] 2024-08-11 06:09
Fixed in https://github.com/DevToys-app/DevToys/pull/1371/files for Chinese and Japanese.

**Closed** 2024-08-11 06:09 UTC
Labels: bug
