### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by SoftExpert** [DevToys-app/DevToys#1446] opened 2024-11-09 06:08 UTC
### Current behavior

Hello,

On my Arch system the last version that opens with an usable UI is 2.0.2.0.
All versions after this one are just opening a blank window.
My current system has an AMD 780M GPU.
I had the same behavior also on a Manjaro system, with Nvidia GPU.

### How to reproduce it (as minimally and precisely as possible)

The easiest way to reproduce: 
1. download the devtoys_linux_x64_portable.zip and extract it to a local folder; any version starting from 2.0.3.0 will do (just tested the 2.0.6.0, it's the same issue)
2. launch ./DevToys.Linux

### Expected behavior

Expecting to see the GUI.

### Screenshots

![image](https://github.com/user-attachments/assets/cc4978f0-dc76-4981-9a35-2c9b05917067)

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0.3.0 onwards | X64

### Relevant Assets/Logs

`
2024-11-09T07:06:11.7298655+01:00	Information	[DevToys.Core.FileHelper]	[0]	Cleared temp files in 0.3277ms
2024-11-09T07:06:11.7356413+01:00	Information	[DevToys.Core.Mef.MefComposer]	[LogDiscoveringPlugin]	Discovering plugin in '/home/user/Public/DevToys/Plugins/DevToys.Tools'...
2024-11-09T07:06:11.7980892+01:00	Information	[DevToys.Core.Mef.MefComposer]	[LogMefComposition]	MEF composed 112 parts from 6 assemblies in 63.7404ms
2024-11-09T07:06:11.8117300+01:00	Information	[DevToys.Linux.LinuxProgram]	[2]	MEF, services and logging initialized in 276.2715 ms
2024-11-09T07:06:11.8117730+01:00	Information	[DevToys.Linux.LinuxProgram]	[1]	App is starting...
2024-11-09T07:06:11.8338352+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64ImageEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8338682+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64TextEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8338712+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CertificateDecoder' tool instance manager.
2024-11-09T07:06:11.8338726+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ColorBlindnessSimulator' tool instance manager.
2024-11-09T07:06:11.8338739+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CronParser' tool instance manager.
2024-11-09T07:06:11.8338762+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'DateConverter' tool instance manager.
2024-11-09T07:06:11.8338775+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'EscapeUnescape' tool instance manager.
2024-11-09T07:06:11.8338787+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'GZipEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8338806+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HashAndChecksumGenerator' tool instance manager.
2024-11-09T07:06:11.8338820+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HtmlEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8338837+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ImageConverter' tool instance manager.
2024-11-09T07:06:11.8338850+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonFormatter' tool instance manager.
2024-11-09T07:06:11.8338866+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JSONPathTester' tool instance manager.
2024-11-09T07:06:11.8338885+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonTableConverter' tool instance manager.
2024-11-09T07:06:11.8338899+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonWebTokenEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8338911+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonYamlConverter' tool instance manager.
2024-11-09T07:06:11.8338930+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ListCompare' tool instance manager.
2024-11-09T07:06:11.8338946+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'LoremIpsumGenerator' tool instance manager.
2024-11-09T07:06:11.8338958+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'MarkdownPreview' tool instance manager.
2024-11-09T07:06:11.8338976+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NumberBaseConverter' tool instance manager.
2024-11-09T07:06:11.8338989+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'PasswordGenerator' tool instance manager.
2024-11-09T07:06:11.8339001+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'QRCodeEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8339021+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'RegExTester' tool instance manager.
2024-11-09T07:06:11.8339033+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'SqlFormatter' tool instance manager.
2024-11-09T07:06:11.8339045+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextAnalyzerAndUtilities' tool instance manager.
2024-11-09T07:06:11.8339066+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextCompare' tool instance manager.
2024-11-09T07:06:11.8339078+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UrlEncoderDecoder' tool instance manager.
2024-11-09T07:06:11.8339089+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UUIDGenerator' tool instance manager.
2024-11-09T07:06:11.8339110+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XmlFormatter' tool instance manager.
2024-11-09T07:06:11.8339122+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XMLTester' tool instance manager.
2024-11-09T07:06:11.8343842+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Extensions Manager' tool instance manager.
2024-11-09T07:06:11.8343936+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Settings' tool instance manager.
2024-11-09T07:06:11.8346612+01:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NoSearchResults' tool instance manager.
2024-11-09T07:06:11.8360722+01:00	Information	[DevToys.Core.Tools.GuiToolProvider]	[LogToolInstancesCreated]	Instantiated 32 tools in 4.3309ms
2024-11-09T07:06:16.9750408+01:00	Information	[DevToys.Core.FileHelper]	[0]	Cleared temp files in 0.0142ms

`

**Comment by ijash** [comment] 2024-11-10 10:32
i think this is the same issue with https://github.com/DevToys-app/DevToys/issues/1438

**Comment by sahrohit** [comment] 2024-11-10 18:03
having the same issue.

**Comment by muuvmuuv** [comment] 2024-11-10 20:43
Yes since latest update. Do we need to install each module manually now?

**Comment by sinnyn** [comment] 2024-11-11 04:17
Seems like in the latest update, no default tools existed in the left panel.  Mac+M2+Sonoma

**Comment by shivarajd** [comment] 2024-11-11 06:54
No default tools available on macOS Sequoia 15.1 with M1 Apple Silicon.
<img width="1552" alt="Screenshot 2024-11-11 at 12 01 01" src="https://github.com/user-attachments/assets/2a0ac678-5076-45fb-8c8d-fb1b9e78534c">

**Comment by veler** [comment] 2024-11-11 07:02
Hi,
The issue you're seeing on MacOS is unrelated to the issue OP mentioned on Linux.
The one on MacOS just got solved in [2.0.7.0](https://github.com/DevToys-app/DevToys/releases/tag/v2.0.7.0). I'm currently pushing it to Homebrew. Should be available in a few hours.

**Comment by shivarajd** [comment] 2024-11-11 11:40
Happy to report that the issue has been fixed in macOS.

**Comment by Red-F** [comment] 2024-11-13 08:12
Blank window on Pop!_OS with version 2.0.7

**Comment by awebcreative** [comment] 2024-11-14 07:40
The same issue on Ubuntu 24.04.1 LTS

**Comment by miseeger** [comment] 2024-11-16 10:49
Also Blank window on Linux Mint and Zorin OS, both current versions. Also tried it on fresh installations in a VM. Same result.

**Comment by ccot7** [comment] 2024-11-17 10:50
Same issue on Fedora 41, GNOME 47.1 . Will try v2.0.2.0 as other mentioned to see if it works.

**Comment by veler** [comment] 2024-11-17 17:01
Hello,

Thanks everyone for your feedback and sorry for my late answer here.

It clearly sounds like something regressed between 2.0.2.0 and 2.0.3.0. The BlazorWebView has been restructured a lot a that time to avoid some race conditions when navigating from a tool to another.
At that time, another bug got fixed, causing blank window too. And it was a single line fix: https://github.com/DevToys-app/DevToys/blob/453ffd1b342ad4237fa9b8f7c03589383bc8ab0b/src/app/dev/platforms/desktop/DevToys.Linux/Components/BlazorWebView/BlazorWebView.cs#L213

The fix in question is to NOT use hardware acceleration in the web browser. I'm wondering if this could be the root cause of the issue you folks are facing. Again, I'm not reproducing the issue on my side. I could try to share a build with this line being changed to see if it works on your machine maybe, or you could try changing this line and build it on your machine, if you're willing to. @ccot7 , @miseeger @awebcreative , @Red-F @SoftExpert .

**Comment by miseeger** [comment] 2024-11-17 17:42
I can also give it a try building it on my machine and I hope it will succeed. The build steps are also of interest for me.

**Comment by veler** [comment] 2024-11-17 17:53
Actually, I probably made it easy for everyone here. I just built DevToys 2.0.7.0 but changed that one line from `Never` to `Always`. On my Linux Mint virtual machine, I do get a blank window (but not when using Never). Can you folks please tell me if you get something different on your side?

To run it, extract the ZIP and run `DevToys.Linux` file:
https://1drv.ms/f/s!AtZ0bJ-3VAYrgbHWHuRofiSD8zRTGpU?e=sHnPgP

**Comment by ccot7** [comment] 2024-11-17 18:04
> Actually, I probably made it easy for everyone here. I just built DevToys 2.0.7.0 but changed that one line from `Never` to `Always`. On my Linux Mint virtual machine, I do get a blank window (but not when using Never). Can you folks please tell me if you get something different on your side?
> 
> To run it, extract the ZIP and run `DevToys.Linux` file: https://1drv.ms/f/s!AtZ0bJ-3VAYrgbHWHuRofiSD8zRTGpU?e=sHnPgP
> 
> If you're still interested in building and playing with the code yourself, you can follow instructions here: https://github.com/DevToys-app/DevToys/blob/main/CONTRIBUTING.md#from-linux

Tried it, still same issue (fedora 41, GNOME 47.1) so on my end nothing to do with hardware acceleration.

Here is my log:
>2024-11-17T20:03:11.3263174+02:00	Information	[DevToys.Core.FileHelper]	[0]	Cleared temp files in 0.9689ms
2024-11-17T20:03:11.3394605+02:00	Information	[DevToys.Core.Mef.MefComposer]	[LogDiscoveringPlugin]	Discovering plugin in '/home/shades/Downloads/X64_devtoys_always_hardware_acceleration/Plugins/DevToys.Tools'...
2024-11-17T20:03:11.5705264+02:00	Information	[DevToys.Core.Mef.MefComposer]	[LogMefComposition]	MEF composed 112 parts from 6 assemblies in 233.3972ms
2024-11-17T20:03:11.6041215+02:00	Information	[DevToys.Linux.LinuxProgram]	[2]	MEF, services and logging initialized in 659.9507 ms
2024-11-17T20:03:11.6042224+02:00	Information	[DevToys.Linux.LinuxProgram]	[1]	App is starting...
2024-11-17T20:03:11.7079681+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64ImageEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7086465+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64TextEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7091924+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CertificateDecoder' tool instance manager.
2024-11-17T20:03:11.7097136+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ColorBlindnessSimulator' tool instance manager.
2024-11-17T20:03:11.7102426+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CronParser' tool instance manager.
2024-11-17T20:03:11.7107544+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'DateConverter' tool instance manager.
2024-11-17T20:03:11.7112964+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'EscapeUnescape' tool instance manager.
2024-11-17T20:03:11.7118022+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'GZipEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7123525+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HashAndChecksumGenerator' tool instance manager.
2024-11-17T20:03:11.7128620+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HtmlEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7133846+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ImageConverter' tool instance manager.
2024-11-17T20:03:11.7138913+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonFormatter' tool instance manager.
2024-11-17T20:03:11.7144092+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JSONPathTester' tool instance manager.
2024-11-17T20:03:11.7149102+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonTableConverter' tool instance manager.
2024-11-17T20:03:11.7154724+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonWebTokenEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7159818+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonYamlConverter' tool instance manager.
2024-11-17T20:03:11.7165020+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ListCompare' tool instance manager.
2024-11-17T20:03:11.7170073+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'LoremIpsumGenerator' tool instance manager.
2024-11-17T20:03:11.7175237+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'MarkdownPreview' tool instance manager.
2024-11-17T20:03:11.7180264+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NumberBaseConverter' tool instance manager.
2024-11-17T20:03:11.7185435+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'PasswordGenerator' tool instance manager.
2024-11-17T20:03:11.7190456+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'QRCodeEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7195729+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'RegExTester' tool instance manager.
2024-11-17T20:03:11.7200880+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'SqlFormatter' tool instance manager.
2024-11-17T20:03:11.7205966+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextAnalyzerAndUtilities' tool instance manager.
2024-11-17T20:03:11.7211120+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextCompare' tool instance manager.
2024-11-17T20:03:11.7216145+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UrlEncoderDecoder' tool instance manager.
2024-11-17T20:03:11.7221310+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UUIDGenerator' tool instance manager.
2024-11-17T20:03:11.7226400+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XmlFormatter' tool instance manager.
2024-11-17T20:03:11.7231737+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XMLTester' tool instance manager.
2024-11-17T20:03:11.7247131+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Extensions Manager' tool instance manager.
2024-11-17T20:03:11.7250489+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Settings' tool instance manager.
2024-11-17T20:03:11.7257257+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NoSearchResults' tool instance manager.
2024-11-17T20:03:11.7289110+02:00	Information	[DevToys.Core.Tools.GuiToolProvider]	[LogToolInstancesCreated]	Instantiated 32 tools in 26.2644ms
2024-11-17T20:03:23.9271122+02:00	Information	[DevToys.Core.FileHelper]	[0]	Cleared temp files in 0.0427ms

**Comment by veler** [comment] 2024-11-17 18:19
Thanks @ccot7 ! The logs aren't helpful at the moment unfortunately. Let's try something different then. I reverted to `Never`. Now I enabled the access to the developer tools of the WebView that is supposed to show the whole UI. With the same link below, you should be able to do a right-click on the blank window, and access `Inspect Element`. 

https://1drv.ms/f/s!AtZ0bJ-3VAYrgbHWHuRofiSD8zRTGpU?e=sHnPgP

![image](https://github.com/user-attachments/assets/1703f15b-d0df-4b07-bdc6-d5f05e101179)

In the dev tools, can you please access the `Console` tab and share whether you see any errors?

If you do **not** see the `Inspect Element` menu, then that likely means the WebView doesn't load at all somehow.

**Comment by ccot7** [comment] 2024-11-17 19:00
@veler I see Inspect element. In the console I don't see any errors, only this:
![image](https://github.com/user-attachments/assets/f9d74958-bc61-4d14-a96f-575136d944a2)

When I click on 'element' the page html is empty like if nothing is generated html wise, ie: 
![image](https://github.com/user-attachments/assets/a386ca75-8e54-4914-a669-d249c90173d5)

I check 'sources' and there seems only 1 js script loaded:
![image](https://github.com/user-attachments/assets/6b58ecb0-af32-4082-87a0-02abc0f9d07d)

Network tab seems no calls:
![image](https://github.com/user-attachments/assets/e7121034-b3b2-46a3-b374-d4b14f374ce2)

**Comment by veler** [comment] 2024-11-17 19:31
> @veler I see Inspect element. In the console I don't see any errors, only this: ![image](https://private-user-images.githubusercontent.com/160058510/386990013-f9d74958-bc61-4d14-a96f-575136d944a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE4ODIsIm5iZiI6MTczMTg3MTU4MiwicGF0aCI6Ii8xNjAwNTg1MTAvMzg2OTkwMDEzLWY5ZDc0OTU4LWJjNjEtNGQxNC1hOTZmLTU3NTEzNmQ5NDRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmNiMzAwMjU4NTE3MDMwYTgwMzBjNWIxNzU5NGZlNzBlZmY0OGM3ZTc4YTE3NTY4MmUyZTJhZGI5ZjgwYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m6RPLx_yq8wCQPByNqsBwZc-S8aGJ50BhfMMhYC46SU)
> 
> When I click on 'element' the page html is empty like if nothing is generated html wise, ie: ![image](https://private-user-images.githubusercontent.com/160058510/386990137-a386ca75-8e54-4914-a669-d249c90173d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE4ODIsIm5iZiI6MTczMTg3MTU4MiwicGF0aCI6Ii8xNjAwNTg1MTAvMzg2OTkwMTM3LWEzODZjYTc1LThlNTQtNDkxNC1hNjY5LWQyNDljOTAxNzNkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmYzNzlkYjcwMjE0ZjU3MmVlYzE0MTVlYWY2NzZhZTcwOGI0MTRmNzVlODlhYjhkMTQ3MjNmYmE3NjU2NDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2-eYC09seJBBgkVDZd59m6mtJBnEM6hNof-dWO5XRXA)
> 
> I check 'sources' and there seems only 1 js script loaded: ![image](https://private-user-images.githubusercontent.com/160058510/386990377-6b58ecb0-af32-4082-87a0-02abc0f9d07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE4ODIsIm5iZiI6MTczMTg3MTU4MiwicGF0aCI6Ii8xNjAwNTg1MTAvMzg2OTkwMzc3LTZiNThlY2IwLWFmMzItNDA4Mi04N2EwLTAyYWJjMGY5ZDA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTdlZmY3OWZkOWM0ZmViODA4NDQ5ZTY2NGJkZTcwY2UwMjI4M2EwYjEzODQzMGZiMWMwMTNkMTYyMzBiNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p6orbMXBKSRyB30aPkpvpW_AtpEe-7kwGd33J27fgmw)
> 
> Network tab seems no calls: ![image](https://private-user-images.githubusercontent.com/160058510/386990562-e7121034-b3b2-46a3-b374-d4b14f374ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE4ODIsIm5iZiI6MTczMTg3MTU4MiwicGF0aCI6Ii8xNjAwNTg1MTAvMzg2OTkwNTYyLWU3MTIxMDM0LWIzYjItNDZhMy1iMzc0LWQ0YjE0ZjM3NGNlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2M4YWMxNjE5MjEyMTViMTM2MDNmOWQ0YzY1OWUxZDIzYTY5YTcyOGViYjA4Mjk0ODU3Yjk4YTIxZTliMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w7qpL0El1e-gYayxNCLrfoOCd5d0WzIbMW_sA7jpQY4)
> 
> Btw not sure if relevant, but here is what gets displayed in my terminal while ./Devtoys.linux is executed: ![image](https://private-user-images.githubusercontent.com/160058510/386990863-3f963d9f-2e6f-4d23-ac24-003a02a3095b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzE4ODIsIm5iZiI6MTczMTg3MTU4MiwicGF0aCI6Ii8xNjAwNTg1MTAvMzg2OTkwODYzLTNmOTYzZDlmLTJlNmYtNGQyMy1hYzI0LTAwM2EwMmEzMDk1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxOTI2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGJmNWMwNDJhMTkwMTRmMjkyNmZkZjE4ZTA5ZmVhNDc1ZWRhZjIyNjg5Yjk3NjkzMWQ3NDJjMDhkZWYxZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.awhN079SEQGAQulH0PmAB_eQfqikYf5ByiEp4O_70No)

Hi @badcel :-) I hope it's OK to ping you here. Looking at the screenshots, it seems like the [BlazorInitScript](https://github.com/DevToys-app/DevToys/blob/453ffd1b342ad4237fa9b8f7c03589383bc8ab0b/src/app/dev/platforms/desktop/DevToys.Linux/Components/BlazorWebView/BlazorWebView.cs#L27) got injected into the web page, but somehow it did not navigated (yet??) to [index.html](https://github.com/DevToys-app/DevToys/blob/453ffd1b342ad4237fa9b8f7c03589383bc8ab0b/src/app/dev/platforms/desktop/DevToys.Linux/MainWindow.cs#L67). I'm thinking of it because the HTML code seems blank. Any idea what could cause this?

**Comment by ccot7** [comment] 2024-11-17 20:08
@veler  Cannot upload .nettrace file here (github dont support this type). I converted it to speedscope.json which you can view on : https://www.speedscope.app/ 
[DevToys.Linux_20241117_212730.speedscope.json](https://github.com/user-attachments/files/17792231/DevToys.Linux_20241117_212730.speedscope.json)

**Comment by veler** [comment] 2024-11-17 21:31
Thank you @ccot7 ! This is super helpful! I took a trace on my machine too and compared them. I found something interesting. On my machine (where it works), the [HandleUriScheme](https://github.com/DevToys-app/DevToys/blob/453ffd1b342ad4237fa9b8f7c03589383bc8ab0b/src/app/dev/platforms/desktop/DevToys.Linux/Components/BlazorWebView/BlazorWebView.cs#L239) callback is correctly invoked as soon as we navigate to `index.html`. But it doesn't happen on your machine somehow.

I actually battled a similar issue on MacOS not too long ago. The fix was to change the URL we're pointing to from `0.0.0.0` to to `localhost` and it worked.
https://github.com/dotnet/maui/issues/23390#issuecomment-2201896358

So, therefore, let's try the same thing on Linux.
Can you please give a try at the following new build and let me know if it works for you?
https://1drv.ms/f/s!AtZ0bJ-3VAYrgbHWHuRofiSD8zRTGpU?e=FRk8jV

**Comment by ccot7** [comment] 2024-11-17 21:42
Yep this worked :) this has to do with Ipv4/Ipv6 parsing of local address. I had this issue several years ago during an interview, I was connecting to a mongo db on localhost which worked at my home, but when i ran the demo at the company (probably theirs opened Ipv6) it couldnt connect. So I had to debug during the interview and when i used 127.0.0.1 it worked.
In your case it is something similar related to ipv4/ipv6. Check on stackoverflow they have a good explanation: https://stackoverflow.com/questions/73133094/why-can-i-connect-to-mongo-in-node-using-127-0-0-1-but-not-localhost

Congrats, this works now - at least on Fedora 41. Technically should work for others, if anyone here on linux (other distros) please try the localhost fix and tell us if it works.

Thank you @veler for this wonderful tool, merci beaucoup

**Comment by veler** [comment] 2024-11-17 21:45
> Yep this worked :) this has to do with Ipv4/Ipv6 parsing of local address. I had this issue several years ago during an interview, I was connecting to a mongo db on localhost which worked at my home, but when i ran the demo at the company (probably theirs opened Ipv6) it couldnt connect. So I had to debug during the interview and when i used 127.0.0.1 it worked. In your case it is something similar related to ipv4/ipv6. Check on stackoverflow they have a good explanation: https://stackoverflow.com/questions/73133094/why-can-i-connect-to-mongo-in-node-using-127-0-0-1-but-not-localhost
> 
> Congrats, this works now - at least on Fedora 41. Technically should work for others, if anyone here on linux (other distros) please try the localhost fix and tell us if it works.
> 
> Thank you @veler for this wonderful tool, merci beaucoup

Oh dear, no, thank you to you! :D I was getting frustrated and ashamed that this issue existed for so many people yet I couldn't reproduce it! :D I'm gonna try it on a few other distribution just to make sure the ones where it work (all my VM have it working properly... Ubuntu, Mint, Fedora...) still work, and ship an update ASAP!

Thank you again @ccot7 !

**Comment by ccot7** [comment] 2024-11-17 21:50
Ashamed? man you should be given a medal for this tool, lovely and pretty efficient tool.

keep up the good work, cheers! @veler

**Comment by miseeger** [comment] 2024-11-17 22:06
Hi @veler and @ccot7, sorry for being too late to the show. All I could have done was testing the "localhost" version and it works perfectly also on Linux Mint 22 (Cinamon). You did awesome things, on this sunday evening. Thank you both, so much !!!

**Closed** 2024-11-17 22:13 UTC
Labels: bug, untriaged, platforms:Linux, app-kind:GUI

**Comment by veler** [comment] 2024-11-17 22:53
Release is available :)
https://github.com/DevToys-app/DevToys/releases/tag/v2.0.8.0

**Comment by miseeger** [comment] 2024-11-18 18:40
Working like a charm, again 💖

**Comment by Red-F** [comment] 2024-11-19 13:03
Yep, also works fine on Pop!_OS again. Thanks!
